using System.Reflection;
using AgriLedger.Application.Interfaces;
using ClosedXML.Excel;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace AgriLedger.Infrastructure.Reporting;

// Generic Excel/PDF export used by every report endpoint. Uses reflection over the
// row DTO's public properties so new report types don't need bespoke export code.
public class ReportExportService : IReportExportService
{
    public ReportExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] ExportToExcel<T>(List<T> rows, string sheetName)
    {
        var props = typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance);

        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add(sheetName);

        for (int col = 0; col < props.Length; col++)
            sheet.Cell(1, col + 1).Value = SplitPascalCase(props[col].Name);
        sheet.Row(1).Style.Font.Bold = true;

        for (int row = 0; row < rows.Count; row++)
        {
            for (int col = 0; col < props.Length; col++)
            {
                var value = props[col].GetValue(rows[row]);
                sheet.Cell(row + 2, col + 1).Value = value?.ToString() ?? "";
            }
        }
        sheet.Columns().AdjustToContents();

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public byte[] ExportToPdf<T>(List<T> rows, string title, IEnumerable<string> columnHeaders, Func<T, IEnumerable<string>> rowSelector)
    {
        var headers = columnHeaders.ToList();

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Landscape());
                page.Margin(24);
                page.Header().Text(title).FontSize(16).Bold();

                page.Content().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        foreach (var _ in headers) columns.RelativeColumn();
                    });

                    table.Header(header =>
                    {
                        foreach (var h in headers)
                            header.Cell().Background(Colors.Green.Lighten3).Padding(4).Text(h).Bold();
                    });

                    foreach (var row in rows)
                    {
                        foreach (var cell in rowSelector(row))
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(4).Text(cell);
                    }
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by AgriLedger — ");
                    x.Span(DateTime.Now.ToString("dd MMM yyyy HH:mm"));
                });
            });
        });

        return document.GeneratePdf();
    }

    private static string SplitPascalCase(string input) =>
        System.Text.RegularExpressions.Regex.Replace(input, "(?<!^)([A-Z])", " $1");
}
